version: '3.8'

services:
  test_db:
    image: postgres:13
    env_file:
      - ./test.env
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  test_api:
    build: .
    env_file:
      - ./test.env
    ports:
      - "8001:8000"
    depends_on:
      - test_db
    mem_limit: 4g
    command: bash
